// 빌드된 dist/pi-canvas.html 을 실제 브라우저(file://)로 열어 사전과제 흐름 전체를 점검한다.
// 사용: npm run build && node scripts/smoke.mjs [스크린샷 폴더]
import { chromium } from 'playwright'
import { readFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'

const shotDir = resolve(process.argv[2] ?? 'dist/smoke')
mkdirSync(shotDir, { recursive: true })
const url = 'file://' + resolve('dist/pi-canvas.html')

const browser = await chromium.launch()
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true, locale: 'ko-KR' })
const page = await context.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(String(e)))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
page.on('dialog', (d) => d.accept())
// 외부 요청이 하나라도 있으면 사내망에서 깨진다
const external = []
page.on('request', (r) => { if (!r.url().startsWith('file:') && !r.url().startsWith('data:') && !r.url().startsWith('blob:')) external.push(r.url()) })

const step = (name) => console.log('•', name)
const assert = (cond, msg) => { if (!cond) throw new Error('검증 실패: ' + msg) }
const shot = (name) => page.screenshot({ path: `${shotDir}/${name}.png` }).catch((e) => console.log('  (스크린샷 생략: ' + e.message.split('\n')[0] + ')'))

await page.goto(url)
step('첫 실행 도움말')
await page.getByRole('dialog', { name: '사용 안내' }).waitFor()
await shot('01-help')
await page.getByRole('button', { name: '시작하기' }).click()

step('작성자·프로세스 입력')
await page.locator('[data-field="meta.author"]').fill('김테스트')
await page.locator('[data-field="meta.dept"]').fill('인사팀')
await page.locator('[data-field="tax.l1"]').selectOption({ label: '인사' })
await page.locator('[data-field="tax.l2"]').selectOption({ label: '보상' })
await page.locator('[data-field="tax.l3"]').selectOption({ label: '급여' })
await page.locator('[data-field="process.name"]').fill('월 급여 지급')
await page.locator('[data-field="process.startEvent"]').fill('근태 마감')
await page.locator('[data-field="process.endEvent"]').fill('급여 입금 및 명세서 발송')
await page.locator('[data-field="process.customer"]').fill('임직원')

step('L5 활동 표 헤더 확인 (부서 열 제거 · 시스템/프로그램 개칭 · Input/Output 추가)')
const headers = await page.locator('.act-table thead th').allInnerTexts()
assert(!headers.some((h) => h.includes('부서')), "'부서' 열이 없어야 함: " + headers.join(','))
assert(headers.some((h) => h.includes('시스템/프로그램')), "'시스템/프로그램' 열 이름: " + headers.join(','))
assert(headers.includes('Input') && headers.includes('Output'), 'Input/Output 열: ' + headers.join(','))
assert((await page.locator('[data-field="row.dept"]').count()) === 0, 'row.dept 입력칸이 없어야 함')
assert(headers.indexOf('비고') === headers.length - 2, "'비고'는 (행 편집 칸 바로 앞) 가장 오른쪽 데이터 열이어야 함: " + headers.join(','))

step('표 입력 + Enter 이동 (한글)')
const rowInputs = (field) => page.locator(`[data-field="${field}"]`)
await rowInputs('row.performer').nth(0).fill('인사팀')
await rowInputs('row.performer').nth(0).press('Enter')
await page.keyboard.type('재무팀')
await rowInputs('row.performer').nth(2).fill('인사팀')
await rowInputs('row.name').nth(0).fill('근태 데이터 수집')
await rowInputs('row.name').nth(1).fill('급여 대장 검토')
await rowInputs('row.name').nth(2).fill('급여 확정 여부 판단')
await rowInputs('row.name').nth(2).press('Enter') // 마지막 행 → 새 행
assert((await rowInputs('row.name').count()) === 4, '마지막 행 Enter 로 새 행 생성')
await page.keyboard.type('급여 이체')
await rowInputs('row.performer').nth(3).fill('재무팀')
assert((await rowInputs('row.name').nth(2).inputValue()) === '급여 확정 여부 판단', 'Enter 직후 입력이 이전 행에 섞이지 않음')
assert((await rowInputs('row.name').nth(3).inputValue()) === '급여 이체', '새 행에 입력')
assert((await rowInputs('row.performer').nth(0).inputValue()) === '인사팀' && (await rowInputs('row.performer').nth(1).inputValue()) === '재무팀', '담당자 Enter 이동 (스윔레인 기준)')

step('판단 행 + 아직 없는 순번 연결')
await page.locator('[data-field="row.kind"]').nth(2).selectOption('decision')
await rowInputs('row.next').nth(2).fill('확정→4, 수정→2, 보류→6')
await rowInputs('row.next').nth(2).blur()
assert((await page.locator('.issues').innerText()).includes('"6"번이 없습니다'), '없는 순번 경고')

step('도구 선택 팝업')
await page.locator('[data-field="row.tools"]').nth(0).click()
await page.locator('.tools-pop').getByRole('button', { name: 'HRIS' }).click()
await page.locator('.tools-pop').getByRole('button', { name: '엑셀' }).click()
await page.locator('.tools-pop input').fill('근태시스템')
await page.locator('.tools-pop input').press('Enter')
await page.locator('.tools-pop').getByRole('button', { name: '확인' }).click()
assert((await page.locator('[data-field="row.tools"]').nth(0).innerText()).includes('근태시스템'), '사용자 정의 도구 추가')

step('엑셀 붙여넣기 (헤더 포함) → 뒤에 추가')
await page.getByRole('button', { name: '표 붙여넣기' }).click()
await page.locator('.paste-area').fill('담당자\t활동명\t시스템\n재무팀\t이체 결과 확인\t이메일, Excel\n인사팀\t급여 명세서 발송\tHRIS')
await page.getByRole('button', { name: /2행 뒤에 추가/ }).click()
assert((await rowInputs('row.name').count()) === 6, '붙여넣기 후 6행')
assert(!(await page.locator('.issues').innerText()).includes('"6"번이 없습니다'), '6번 행이 생기면 보류 링크 확정')
assert((await rowInputs('row.next').nth(2).inputValue()) === '확정→4, 수정→2, 보류→6', '다음 단계 표시')

step('행 이동 후에도 링크 유지')
await page.locator('.row-actions').nth(1).getByTitle('아래로').click() // 2번 ↔ 3번
assert((await rowInputs('row.next').nth(1).inputValue()) === '확정→4, 수정→3, 보류→6', '이동 후 순번 재계산')

step('행 삭제 → 되돌리기')
await page.locator('.row-actions').nth(5).getByTitle('행 삭제').click()
assert((await rowInputs('row.name').count()) === 5, '삭제')
await page.locator('.toast').getByRole('button', { name: '되돌리기' }).click()
assert((await rowInputs('row.name').count()) === 6, '되돌리기')

await shot('02-filled')

step('순서도 편집 탭')
const tab = (name) => page.getByRole('tab', { name })
const node = (id) => page.locator(`.react-flow__node[data-id="${id}"]`)
const nodeByName = (name) => page.locator('.react-flow__node', { hasText: name })
const center = async (loc) => { const b = await loc.boundingBox(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 } }
const drag = async (from, to) => {
  await page.mouse.move(from.x, from.y); await page.mouse.down()
  await page.mouse.move(to.x, to.y, { steps: 10 }); await page.mouse.up()
  await page.waitForTimeout(150)
}
const lanesText = async () => (await page.locator('.fx-lane-name').allInnerTexts()).join(',')
await tab(/순서도 편집/).click()
await page.locator('.react-flow__node-task').first().waitFor()
const tasks = await page.locator('.react-flow__node-task').count()
const gws = await page.locator('.react-flow__node-decision').count()
assert(tasks === 5 && gws === 1, `순서도 노드 수 task=${tasks} gw=${gws}`)
assert((await lanesText()) === '인사팀,재무팀', '레인 = 담당자 ' + (await lanesText()))
assert((await page.locator('.react-flow__edge').count()) >= 7, '연결선')
await shot('02b-canvas')

step('순서도: 박스를 다른 레인으로 끌면 담당자가 바뀐다 → Ctrl+Z / Ctrl+Y')
const payTransfer = nodeByName('급여 이체')
await drag(await center(payTransfer), await center(page.locator('.fx-lane-label').nth(0)).then((c) => ({ x: c.x + 600, y: c.y })))
await tab(/과제 정보/).click()
assert((await rowInputs('row.performer').nth(3).inputValue()) === '인사팀', '레인 이동 → 담당자 변경')
await tab(/순서도 편집/).click()
await page.keyboard.press('Control+z')
await tab(/과제 정보/).click()
assert((await rowInputs('row.performer').nth(3).inputValue()) === '재무팀', 'Ctrl+Z 되돌리기')
await tab(/순서도 편집/).click()
await page.keyboard.press('Control+y')
await page.keyboard.press('Control+z')

step('순서도: 팔레트에서 활동 추가 → 이름 입력 → 연결 → 표에 반영')
await page.getByRole('button', { name: '전체 보기' }).click()
await page.waitForTimeout(300)
const canvasBox = await page.locator('.fx-canvas').boundingBox()
const lane1 = await center(page.locator('.fx-lane-label').nth(1))
const lastBox = await center(nodeByName('급여 명세서 발송'))
await page.locator('.fx-palette.task').dragTo(page.locator('.fx-canvas'), { targetPosition: { x: lastBox.x - canvasBox.x, y: lane1.y - canvasBox.y } })
await page.locator('.fx-name-edit').waitFor()
await page.keyboard.type('지급 결과 보고')
await page.keyboard.press('Enter')
const added = nodeByName('지급 결과 보고')
await added.waitFor()
const source = nodeByName('이체 결과 확인')
await source.hover()
await drag(await center(source.locator('.react-flow__handle-right')), await center(added))
await tab(/과제 정보/).click()
const names = await rowInputs('row.name').evaluateAll((els) => els.map((e) => e.value))
assert(names.includes('지급 결과 보고'), '캔버스에서 추가한 활동이 표에 생김: ' + names.join(','))
const addedIdx = names.indexOf('지급 결과 보고')
assert((await rowInputs('row.performer').nth(addedIdx).inputValue()) === '재무팀', '놓은 레인의 담당자')
const srcIdx = names.indexOf('이체 결과 확인')
assert((await rowInputs('row.next').nth(srcIdx).inputValue()).includes(String(addedIdx + 1)), '연결 → 다음 단계')
await tab(/순서도 편집/).click()

step('순서도: 연결선 끝을 끌어 다른 박스로 옮기기 → 표의 다음 단계')
await page.getByRole('button', { name: '전체 보기' }).click()
await page.waitForTimeout(300)
const reviewId = await nodeByName('급여 대장 검토').getAttribute('data-id')
await page.locator(`.react-flow__edge[data-id="${reviewId}#0"]`).click({ force: true })
await drag(await center(page.locator(`.react-flow__edge[data-id="${reviewId}#0"] .react-flow__edgeupdater-target`)), await center(nodeByName('급여 명세서 발송')))
await tab(/과제 정보/).click()
assert((await rowInputs('row.next').nth(2).inputValue()) === '6', '연결 옮기기 → 다음 단계 6: ' + (await rowInputs('row.next').nth(2).inputValue()))
await tab(/순서도 편집/).click()
await page.keyboard.press('Control+z')

step('순서도: 활동 삭제 시 앞뒤 연결 유지, 레인 이름 바꾸기')
await nodeByName('지급 결과 보고').click()
await page.keyboard.press('Delete')
assert((await nodeByName('지급 결과 보고').count()) === 0, '삭제')
await page.locator('.fx-lane-name').nth(1).click()
await page.locator('.fx-lane-label input').fill('재무팀 담당')
await page.locator('.fx-lane-label input').press('Enter')
assert((await lanesText()) === '인사팀,재무팀 담당', '레인 이름 변경 ' + (await lanesText()))
await shot('02c-canvas-edited')
await tab(/과제 정보/).click()
assert((await rowInputs('row.performer').nth(2).inputValue()) === '재무팀 담당', '레인 이름 → 담당자 일괄 변경')
assert((await rowInputs('row.name').count()) === 6, '삭제 후 6행')

step('엑셀 내보내기 (과제 양식)')
const [xl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /엑셀 내보내기/ }).click()])
assert(xl.suggestedFilename() === '월_급여_지급_김테스트.xlsx', '엑셀 파일명 ' + xl.suggestedFilename())
const xlPath = `${shotDir}/${xl.suggestedFilename()}`
await xl.saveAs(xlPath)
const xlBytes = readFileSync(xlPath)
assert(xlBytes[0] === 0x50 && xlBytes[1] === 0x4b && xlBytes.length > 2000, 'xlsx(zip) 파일')

step('저장(다운로드)')
const [dl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /저장/ }).click()])
assert(dl.suggestedFilename() === '월_급여_지급_김테스트.json', '파일명 ' + dl.suggestedFilename())
const savedPath = `${shotDir}/${dl.suggestedFilename()}`
await dl.saveAs(savedPath)
const saved = JSON.parse(readFileSync(savedPath, 'utf8'))
assert(saved.format === 'pi-canvas' && saved.version === 2, '포맷')
assert(saved.taxonomy.l3.name === '급여' && saved.process.activities.length === 6, '저장 내용')
assert(saved.process.asis?.layout?.lanes?.join(',') === '인사팀,재무팀 담당', '순서도 배치(레인 순서) 저장')
assert(saved.process.activities[1].next.length === 3, '판단 링크 저장')
assert((await page.locator('.save-state').innerText()) === '파일 저장됨', '저장 상태')

step('새로고침 → 임시저장 복구')
await rowInputs('row.note').nth(0).fill('마감 지연 잦음')
await page.reload()
assert((await rowInputs('row.note').nth(0).inputValue()) === '마감 지연 잦음', '임시저장 복구')
assert(!(await page.getByRole('dialog').count()), '두 번째 실행에는 도움말 자동 표시 안 함')

step('예시 보기 → 돌아가기 (내 작업 보존)')
await page.getByRole('button', { name: '예시 보기' }).click()
assert((await page.locator('[data-field="process.name"]').inputValue()) === '채용 요청 및 공고', '예시 로드')
await shot('03-example')
await tab(/순서도 편집/).click()
await page.locator('.react-flow__node-task').first().waitFor()
await shot('03b-example-canvas')
await tab(/과제 정보/).click()
await page.getByRole('button', { name: '내 작성 화면으로 돌아가기' }).click()
assert((await page.locator('[data-field="process.name"]').inputValue()) === '월 급여 지급', '내 작업 보존')

step('새로 만들기 → 저장 파일 열기')
await page.getByRole('button', { name: '새로 만들기' }).click()
assert((await page.locator('[data-field="process.name"]').inputValue()) === '', '새 문서')
await page.locator('input[type=file]').setInputFiles(savedPath)
await page.locator('.toast.ok').waitFor()
assert((await page.locator('[data-field="process.name"]').inputValue()) === '월 급여 지급', '파일 열기')
assert((await rowInputs('row.name').count()) === 6, '열기 후 행 수')

step('잘못된 파일 열기')
await page.locator('input[type=file]').setInputFiles({ name: 'x.json', mimeType: 'application/json', buffer: Buffer.from('{"hello":1}') })
await page.locator('.toast.warn').waitFor()

step('셀에 엑셀 범위 직접 붙여넣기 (Ctrl+V) → 가져오기 창')
await rowInputs('row.note').nth(0).focus()
await page.evaluate(() => {
  const dt = new DataTransfer()
  dt.setData('text/plain', '인사팀\t담당\t지급 결과 보고\n인사팀\t담당\t급여 마감 회의')
  document.activeElement.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true }))
})
await page.getByRole('dialog', { name: '표 붙여넣기' }).waitFor()
assert((await page.locator('.preview-table tbody tr').count()) === 2, '붙여넣기 미리보기 2행')
await page.getByRole('dialog').getByRole('button', { name: '취소' }).click()

step('실전 원본 양식(EXP14.xlsx) 붙여넣기 — 설명 셀 안 화살표 분기·시작/종료 행 인식')
await page.getByRole('button', { name: '새로 만들기' }).click()
assert((await page.locator('[data-field="process.name"]').inputValue()) === '', '새 문서로 초기화')
await page.getByRole('button', { name: '표 붙여넣기' }).click()
const exp14Text = [
  'No.\t설명\t담당자\t시스템/프로그램\tInput\tOutput',
  '시작\t장기부재자 안내 메일을 수신한다\t\t\t\t',
  '01\t명단을 확인한다\t행정사원\tER\t명단\t리스트',
  '02\t"이상 유무를 판단한다\n→ 이상 없음(No) : 종료\n→ 이상 있음(Yes) : 03번으로 진행"\t행정사원\t\t\t',
  '03\t결과를 수정한다\t행정사원\t전용시스템\t\t',
  '종료\t완료되면 종료한다\t\t\t\t',
].join('\n')
await page.locator('.paste-area').fill(exp14Text)
await page.getByRole('button', { name: /가져오기/ }).click()
assert((await rowInputs('row.name').count()) === 3, 'EXP14 시작·종료 행은 제외하고 활동 3개만 생성')
assert((await page.locator('[data-field="process.startEvent"]').inputValue()).includes('장기부재자'), "'시작' 행 문구가 E2E 시작에 자동으로 채워짐")
assert((await page.locator('[data-field="process.endEvent"]').inputValue()).includes('완료되면 종료한다'), "'종료' 행 문구가 E2E 종료에 자동으로 채워짐")
assert((await rowInputs('row.input').nth(0).inputValue()) === '명단', 'Input 열이 엑셀 Input 칸을 그대로 받음 (비고로 합쳐지지 않음)')
assert((await rowInputs('row.output').nth(0).inputValue()) === '리스트', 'Output 열이 엑셀 Output 칸을 그대로 받음')
await tab(/순서도 편집/).click()
await page.locator('.react-flow__node-task').first().waitFor()
assert((await page.locator('.react-flow__node-task').count()) === 2, 'task 노드 2개(01, 03)')
assert((await page.locator('.react-flow__node-decision').count()) === 1, '설명 셀 안 화살표 분기(→ 이상 없음/있음)를 판단 노드로 인식')
await shot('07-exp14-paste')
await tab(/과제 정보/).click()

step('노트북 화면 (1366×768)')
await page.setViewportSize({ width: 1366, height: 768 })
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
assert(overflow <= 0, '페이지 자체는 가로로 넘치면 안 됨(넘침 ' + overflow + 'px) — 표는 .table-wrap 자체 스크롤로 담아야 한다')
// Input/Output 열이 늘어난 만큼 표 자체는 1366px 에서 자체 가로 스크롤이 생길 수 있다(By design: .table-wrap { overflow-x: auto }).
await shot('05-laptop')
await page.locator('.act-table').scrollIntoViewIfNeeded()
await shot('06-laptop-table')
await tab(/순서도 편집/).click()
await page.locator('.react-flow__node-task').first().waitFor()
const canvasOverflow = await page.evaluate(() => [document.documentElement.scrollWidth - window.innerWidth, document.documentElement.scrollHeight - window.innerHeight])
assert(canvasOverflow[0] <= 0 && canvasOverflow[1] <= 0, '순서도 화면은 한 화면에 들어와야 함: ' + canvasOverflow)
await shot('08-laptop-canvas')
await tab(/과제 정보/).click()

await shot('04-reopened')
assert(errors.length === 0, '콘솔 오류: ' + errors.join('\n'))
assert(external.length === 0, '외부 요청: ' + external.join(', '))
console.log(`\n✔ 모든 점검 통과 · 스크린샷: ${shotDir}`)
await browser.close()
